---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: vote-ci
spec:
  pipelineRef:
    name: instavote-ci
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: dockerconfig
    secret:
      secretName: dockerhub-creds
  params:
  - name: repoUrl
    value: https://github.com/initcron/example-voting-app.git
  - name: revision
    value: master
  - name: sparseCheckoutDirectories
    value: /vote/
  - name: imageUrl
    value: cplk01/vote
  - name: pathToContext
    value: vote
